apiVersion: v2
name: lamina
description: S3-compatible storage API service with support for Kubernetes and OpenShift
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - s3
  - storage
  - api
  - dotnet
home: https://github.com/LoyaltyPointHQ/Lamina
sources:
  - https://github.com/LoyaltyPointHQ/Lamina
maintainers:
  - name: LoyaltyPoint Sp. z o. o.
    email: admin@loyaltypoint.io
