apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lamina.fullname" . }}
  labels:
    {{- include "lamina.labels" . | nindent 4 }}
data:
  appsettings.Production.json: |
    {{- if kindIs "string" .Values.config }}
    {{- .Values.config | nindent 4 }}
    {{- else }}
    {{- .Values.config | toPrettyJson | nindent 4 }}
    {{- end }}