apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lamina.fullname" . }}
  labels:
    {{- include "lamina.labels" . | nindent 4 }}
data:
  appsettings.Production.json: |
    {{- $config := deepCopy .Values.config }}
    {{- /* Remove sensitive data from config */ -}}
    {{- if $config.Authentication }}
    {{- if $config.Authentication.Users }}
    {{- range $i, $user := $config.Authentication.Users }}
    {{- $_ := unset $user "AccessKeyId" }}
    {{- $_ := unset $user "SecretAccessKey" }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- /* Handle Redis connection string */ -}}
    {{- $redisConnectionString := include "lamina.redisConnectionString" . }}
    {{- if $redisConnectionString }}
    {{- if not $config.Redis }}
    {{- $_ := set $config "Redis" dict }}
    {{- end }}
    {{- if contains "password=" $redisConnectionString }}
    {{- /* Connection string with password will be handled by environment variable */ -}}
    {{- $_ := unset $config.Redis "ConnectionString" }}
    {{- else }}
    {{- /* Connection string without password can go in configmap */ -}}
    {{- $_ := set $config.Redis "ConnectionString" $redisConnectionString }}
    {{- end }}
    {{- end }}
    {{- if kindIs "string" $config }}
    {{- $config | nindent 4 }}
    {{- else }}
    {{- $config | toPrettyJson | nindent 4 }}
    {{- end }}