{{- if eq (include "lamina.imageStreamEnabled" .) "true" }}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ include "lamina.fullname" . }}
  labels:
    {{- include "lamina.labels" . | nindent 4 }}
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
{{- end }}