{{- if and .Values.secrets .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lamina.fullname" . }}-secrets
  labels:
    {{- include "lamina.labels" . | nindent 4 }}
type: Opaque
data:
  {{- /* Extract authentication secrets from main config */ -}}
  {{- if and .Values.config.Authentication .Values.config.Authentication.Users }}
  {{- range $i, $user := .Values.config.Authentication.Users }}
  {{- if $user.AccessKeyId }}
  auth-user-{{ $i }}-access-key: {{ $user.AccessKeyId | b64enc | quote }}
  {{- end }}
  {{- if $user.SecretAccessKey }}
  auth-user-{{ $i }}-secret-key: {{ $user.SecretAccessKey | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- /* Extract Redis connection string from main config */ -}}
  {{- if and .Values.config.Redis .Values.config.Redis.ConnectionString }}
  {{- if contains "@" .Values.config.Redis.ConnectionString }}
  redis-connection: {{ .Values.config.Redis.ConnectionString | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}