// <auto-generated />
using System;
using Lamina.Storage.Sql.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lamina.Storage.Sql.Migrations.Sqlite
{
    [DbContext(typeof(LaminaDbContext))]
    [Migration("20251003094703_RemoveMultipartUploadPartsRelationship")]
    partial class RemoveMultipartUploadPartsRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Lamina.Storage.Sql.Entities.BucketEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(63)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageClass")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.HasIndex("CreationDate");

                    b.HasIndex("Type");

                    b.ToTable("Buckets");
                });

            modelBuilder.Entity("Lamina.Storage.Sql.Entities.MultipartUploadEntity", b =>
                {
                    b.Property<string>("UploadId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("BucketName")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Initiated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UploadId");

                    b.HasIndex("BucketName");

                    b.HasIndex("Initiated");

                    b.HasIndex("BucketName", "Key");

                    b.ToTable("MultipartUploads");
                });

            modelBuilder.Entity("Lamina.Storage.Sql.Entities.ObjectEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BucketName")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ETag")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BucketName");

                    b.HasIndex("LastModified");

                    b.HasIndex("BucketName", "Key")
                        .IsUnique();

                    b.HasIndex("BucketName", "Key", "LastModified");

                    b.ToTable("Objects");
                });

            modelBuilder.Entity("Lamina.Storage.Sql.Entities.UploadPartEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ETag")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<int>("PartNumber")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UploadId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UploadId", "PartNumber")
                        .IsUnique();

                    b.ToTable("UploadParts");
                });

            modelBuilder.Entity("Lamina.Storage.Sql.Entities.UploadPartEntity", b =>
                {
                    b.HasOne("Lamina.Storage.Sql.Entities.MultipartUploadEntity", "Upload")
                        .WithMany()
                        .HasForeignKey("UploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Upload");
                });
#pragma warning restore 612, 618
        }
    }
}
